version: '3'
services:
  web: #these 2 lines need to included if we use the react app version 3
    stdin_open: true
    # container 1
    build: 
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app

    # container 2 to run teh test
  tests:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] 